const AdminActionTypes = {
  FETCH_ALL_USERS_STARTED: 'FETCH_ALL_USERS_STARTED',
  FETCH_ALL_USERS_SUCCEEDED: 'FETCH_ALL_USERS_SUCCEEDED',
  FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',
  DELETE_USER_STARTED: 'DELETE_USER_STARTED',
  DELETE_USER_FAILED: 'DELETE_USER_FAILED',
  UPDATE_USER_STARTED: 'UPDATE_USER_STARTED',
  UPDATE_USER_SUCCEEDED: 'UPDATE_USER_SUCCEEDED',
  UPDATE_USER_FAILED: 'UPDATE_USER_FAILED'
};
export default AdminActionTypes;
