const PolicyPaperActionTypes = {
  FETCH_ALL_POLICY_PAPER_STARTED: 'FETCH_ALL_POLICY_PAPER_STARTED',
  FETCH_ALL_POLICY_PAPER_SUCCEEDED: 'FETCH_ALL_POLICY_PAPER_SUCCEEDED',
  FETCH_ALL_POLICY_PAPER_FAILED: 'FETCH_ALL_POLICY_PAPER_FAILED',
};
export default PolicyPaperActionTypes;
