const UserActionTypes = {
  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  // SIGNIN_START: 'SIGNIN_START',
  // SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  // SIGNIN_RESET: 'SIGNIN_RESET',
  // SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  // ERROR_RESET: 'ERROR_RESET',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_IN_PROGRESS: 'LOGIN_IN_PROGRESS',
  LOGIN_RESET: 'LOGIN_RESET',
  LOGIN_ERROR: 'LOGIN_ERROR',
  ERROR_RESET: 'ERROR_RESET',
  SIGNOUT_START: 'SIGNOUT_START',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',


};
export default UserActionTypes;
