const UserActionTypes = {
<<<<<<< HEAD
  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_IN_PROGRESS: 'LOGIN_IN_PROGRESS',
  LOGIN_RESET: 'LOGIN_RESET',
  LOGIN_ERROR: 'LOGIN_ERROR',
  ERROR_RESET: 'ERROR_RESET',
=======
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

>>>>>>> created component for signup
};
export default UserActionTypes;
